image: python:3.6

stages:
  - init
  - deploy

init:
  stage: init
  script:
    - pip3 install psycopg2-binary
    - pip3 install -r requirements.txt

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/line-tag-bot.git.git
    - git checkout -B "$CI_BUILD_REF_NAME" "$CI_BUILD_REF"
    - git push heroku
    - echo "Deployed to Production Server https://line-tag-bot.herokuapp.com/"
  environment:
    name: production
    url: https://line-tag-bot.herokuapp.com/
  only:
    - master