# Generated by Django 3.1 on 2020-08-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linegroup',
            name='type',
            field=models.CharField(default='group', max_length=32),
            preserve_default=False,
        ),
    ]
